#!/bin/bash
# Local development uninstall script for nvcontrol
# Removes installed binaries and configurations

set -e

INSTALL_DIR="$HOME/.local/bin"
COMPLETIONS_DIR="$HOME/.local/share/bash-completion/completions"
ZSH_COMPLETIONS_DIR="$HOME/.local/share/zsh/site-functions"
DESKTOP_DIR="$HOME/.local/share/applications"
CONFIG_DIR="$HOME/.config/nvcontrol"
MANGOHUD_CONFIG="$HOME/.config/MangoHud/MangoHud.conf"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║         nvcontrol Local Development Uninstall            ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Parse arguments
REMOVE_CONFIG=false
FORCE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --remove-config)
            REMOVE_CONFIG=true
            shift
            ;;
        --force|-f)
            FORCE=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --remove-config  Also remove configuration files"
            echo "  --force, -f      Don't ask for confirmation"
            echo "  --help, -h       Show this help"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Confirmation
if [[ "$FORCE" == "false" ]]; then
    echo -e "${YELLOW}This will remove:${NC}"
    [[ -f "$INSTALL_DIR/nvctl" ]] && echo "  - $INSTALL_DIR/nvctl"
    [[ -f "$INSTALL_DIR/nvcontrol" ]] && echo "  - $INSTALL_DIR/nvcontrol"
    [[ -f "$COMPLETIONS_DIR/nvctl" ]] && echo "  - $COMPLETIONS_DIR/nvctl"
    [[ -f "$ZSH_COMPLETIONS_DIR/_nvctl" ]] && echo "  - $ZSH_COMPLETIONS_DIR/_nvctl"
    [[ -f "$DESKTOP_DIR/nvcontrol.desktop" ]] && echo "  - $DESKTOP_DIR/nvcontrol.desktop"
    if [[ "$REMOVE_CONFIG" == "true" ]]; then
        [[ -d "$CONFIG_DIR" ]] && echo "  - $CONFIG_DIR/ (config directory)"
        [[ -f "$MANGOHUD_CONFIG" ]] && echo "  - $MANGOHUD_CONFIG (MangoHud config)"
    fi
    echo ""
    read -p "Continue? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Cancelled${NC}"
        exit 0
    fi
fi

echo -e "${YELLOW}🗑️  Removing binaries...${NC}"

# Remove binaries
if [[ -f "$INSTALL_DIR/nvctl" ]]; then
    rm -f "$INSTALL_DIR/nvctl"
    echo -e "${GREEN}  ✅ Removed nvctl${NC}"
fi

if [[ -f "$INSTALL_DIR/nvcontrol" ]]; then
    rm -f "$INSTALL_DIR/nvcontrol"
    echo -e "${GREEN}  ✅ Removed nvcontrol${NC}"
fi

echo -e "${YELLOW}🗑️  Removing shell completions...${NC}"

# Remove completions
if [[ -f "$COMPLETIONS_DIR/nvctl" ]]; then
    rm -f "$COMPLETIONS_DIR/nvctl"
    echo -e "${GREEN}  ✅ Removed bash completions${NC}"
fi

if [[ -f "$ZSH_COMPLETIONS_DIR/_nvctl" ]]; then
    rm -f "$ZSH_COMPLETIONS_DIR/_nvctl"
    echo -e "${GREEN}  ✅ Removed zsh completions${NC}"
fi

echo -e "${YELLOW}🗑️  Removing desktop integration...${NC}"

# Remove desktop file
if [[ -f "$DESKTOP_DIR/nvcontrol.desktop" ]]; then
    rm -f "$DESKTOP_DIR/nvcontrol.desktop"
    echo -e "${GREEN}  ✅ Removed desktop file${NC}"
fi

# Remove config if requested
if [[ "$REMOVE_CONFIG" == "true" ]]; then
    echo -e "${YELLOW}🗑️  Removing configuration...${NC}"

    if [[ -d "$CONFIG_DIR" ]]; then
        rm -rf "$CONFIG_DIR"
        echo -e "${GREEN}  ✅ Removed config directory${NC}"
    fi

    # Only remove MangoHud config if it was generated by nvcontrol
    if [[ -f "$MANGOHUD_CONFIG" ]] && grep -q "nvcontrol" "$MANGOHUD_CONFIG" 2>/dev/null; then
        rm -f "$MANGOHUD_CONFIG"
        echo -e "${GREEN}  ✅ Removed MangoHud config${NC}"
    fi
fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                  Uninstall Complete                      ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

if [[ "$REMOVE_CONFIG" == "false" ]]; then
    echo -e "${YELLOW}Note: Configuration files were kept at:${NC}"
    [[ -d "$CONFIG_DIR" ]] && echo "  - $CONFIG_DIR"
    echo ""
    echo -e "${YELLOW}To also remove configs, run:${NC}"
    echo "  $0 --remove-config"
fi

echo ""
echo -e "${BLUE}To reinstall:${NC} $(dirname "$0")/install.sh"
